export interface Attributes {
  type: string;
  url: string;
}

export interface SFALlAccountFields {
  attributes: Attributes;
  Id: string;
  // IsDeleted: boolean;
  // MasterRecordId: null;
  Account_Name: string;
  Type: string;
  Account_Record_Type: string;
  Parent_Account: string;
  // BillingStreet: string;
  // BillingCity: string;
  // BillingState: string;
  // BillingPostalCode: string;
  // BillingCountry: string;
  // BillingLatitude: string;
  // BillingLongitude: string;
  // BillingGeocodeAccuracy: string;
  Billing_Address: string;
  // ShippingStreet: string;
  ShippingCity: string;
  ShippingState: string;
  ShippingPostalCode: string;
  ShippingCountry: string;
  ShippingLatitude: string;
  ShippingLongitude: string;
  ShippingGeocodeAccuracy: string;
  ShippingAddress: string;
  Phone: string;
  Fax: string;
  Website: string;
  PhotoUrl: string;
  Industry: string;
  AnnualRevenue: string;
  NumberOfEmployees: string;
  Description: string;
  OwnerId: string;
  CreatedDate: string;
  CreatedById: string;
  LastModifiedDate: string;
  LastModifiedById: string;
  SystemModstamp: string;
  LastActivityDate: string;
  LastViewedDate: string;
  LastReferencedDate: string;
  Jigsaw: string;
  JigsawCompanyId: string;
  AccountSource: string;
  SicDesc: string;
  hed__Billing_County__c: string;
  hed__Current_Address__c: string;
  hed__Primary_Contact__c: string;
  hed__School_Code__c: string;
  hed__Shipping_County__c: string;
  k12kit__Elementary_School__c: boolean;
  k12kit__Grade_Levels__c: string;
  k12kit__High_School__c: boolean;
  k12kit__Middle_School__c: boolean;
  k12kit__Pre_school__c: boolean;
  Active__c: string;
  Career_Paths__c: string;
  Employer_Status__c: string;
  Sponsor__c: string;
  Occupations__c: string;
  Notes_Next_Steps__c: string;
  sfal__CaseTeamTemplateName__c: string;
  Record_Type_Name__c: string;
  Listed_by__c: string;
  Category__c: string;
  Venue__c: string;
  End_Date__c: Date;
  Approval_Status__c: string;
  Opportunity_Hidden__c: boolean;
  Opportunity__c: boolean;
  Visibility__c: string;
  message__c: string;
  Start_Date__c: string;
  Event_Assignee__c: string;
  Removal_Status__c: string;
}


