service: palette-persona-service
useDotenv: true

plugins:
  - serverless-offline
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:PALETTE_AWS_REGION}
  apiGateway:
    minimumCompressionSize: 1024
    restApiId: ${env:PALETTE_API_GATEWAY_ID}
    restApiRootResourceId: ${env:PALETTE_API_GATEWAY_ROOT_ID}
  deploymentBucket:
    name: ${env:PALETTE_AWS_STORAGE_BUCKET_NAME}
    serverSideEncryption: AES256
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
  environment:
    JWT_SECRET: ${env:JWT_SECRET}
    PORT: ${env:PORT}
    NODE_ENV: ${env:NODE_ENV}
    PALETTE_AWS_SQS_NOTIFICATION_QUEUE_URL: ${env:PALETTE_AWS_SQS_NOTIFICATION_QUEUE_URL}
    PALETTE_AWS_REGION: ${env:PALETTE_AWS_REGION}
    PALETTE_RUNNER_ACCESS_KEY: ${env:PALETTE_RUNNER_ACCESS_KEY}
    PALETTE_RUNNER_SECRET_KEY: ${env:PALETTE_RUNNER_SECRET_KEY}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: ${env:AWS_NODEJS_CONNECTION_REUSE_ENABLED}

functions:
  # Setup the routes here or an individual function for each persona
  student: 
    handler: dist/lambda.handler  
    events: 
      - http:  
          method: GET
          path: admin/profile
          cors: true
      - http:  
          method: PATCH
          path: admin/profile/update
          cors: true
      - http:  
          method: GET
          path: admin/:id
          cors: true
      - http:  
          method: GET
          path: advisor/profile
          cors: true
      - http:  
          method: PATCH
          path: advisor/profile/update
          cors: true
      - http:  
          method: GET
          path: advisor/:id
          cors: true
      - http:  
          method: GET
          path: observer/profile
          cors: true
      - http:  
          method: PATCH
          path: observer/profile/update
          cors: true
      - http:  
          method: GET
          path: observer/:id
          cors: true
      - http:  
          method: GET
          path: parent/profile
          cors: true
      - http:  
          method: PATCH
          path: parent/profile/update
          cors: true
      - http:  
          method: GET
          path: parent/:id
          cors: true
      - http:  
          method: GET
          path: student/profile
          cors: true
      - http:  
          method: PATCH
          path: student/profile/update
          cors: true
      - http:  
          method: GET
          path: student/:id
          cors: true