service: palette-auth-service
useDotenv: true

plugins:
  - serverless-offline
  - serverless-deployment-bucket
  - serverless-plugin-warmup
  
custom:
  warmup:
    main:
      enabled: true
      events:
        - schedule: cron(0/5 8-17 ? * MON-FRI *)
      concurrency: 10

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:PALETTE_AWS_REGION}
  apiGateway:
    minimumCompressionSize: 1024
    restApiId: ${env:PALETTE_API_GATEWAY_ID}
    restApiRootResourceId: ${env:PALETTE_API_GATEWAY_ROOT_ID}
  deploymentBucket:
    name: ${env:PALETTE_AWS_STORAGE_BUCKET_NAME}
    serverSideEncryption: AES256
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/AmazonSQSFullAccess'
    - 'arn:aws:iam::aws:policy/AWSLambda_FullAccess'
  environment:
    PALETTE_OTP_RESET_TIME: ${env:PALETTE_OTP_RESET_TIME}
    DB_TYPE: ${env:DB_TYPE}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_NAME: ${env:DB_NAME}
    JWT_SECRET: ${env:JWT_SECRET}
    JWT_REFRESH_SECRET: ${env:JWT_REFRESH_SECRET}
    PORT: ${env:PORT}
    DB_SYNC: ${env:DB_SYNC}
    NODE_ENV: ${env:NODE_ENV}
    PASSWORD_HASHING_KEY: ${env:PASSWORD_HASHING_KEY}
    PALETTE_SERVICE_NAME: ${env:PALETTE_SERVICE_NAME}
    PALETTE_AWS_SQS_NOTIFICATION_QUEUE_URL: ${env:PALETTE_AWS_SQS_NOTIFICATION_QUEUE_URL}
    PALETTE_AWS_REGION: ${env:PALETTE_AWS_REGION}
    PALETTE_RUNNER_ACCESS_KEY: ${env:PALETTE_RUNNER_ACCESS_KEY}
    PALETTE_RUNNER_SECRET_KEY: ${env:PALETTE_RUNNER_SECRET_KEY}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: ${env:AWS_NODEJS_CONNECTION_REUSE_ENABLED}


functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: POST
          path: auth/validate
          cors: true
      - http:
          method: POST
          path: auth/login
          cors: true
      - http:
          method: PATCH
          path: auth/password/reset
          cors: true
      - http:
          method: POST
          path: auth/password/forgot
          cors: true
      - http:
          method: POST
          path: auth/password/forgot/validate
          cors: true
      - http:
          method: POST
          path: users/register/pre
          cors: true
      - http:
          method: POST
          path: users/profile/add/picture
          cors: true
      - http:
          method: POST
          path: auth/testing
          cors: true
