service: palette-utility-service
useDotenv: true

plugins:
  - serverless-offline
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:PALETTE_AWS_REGION}
  apiGateway:
    minimumCompressionSize: 1024
    restApiId: ${env:PALETTE_API_GATEWAY_ID}
    restApiRootResourceId: ${env:PALETTE_API_GATEWAY_ROOT_ID}
  deploymentBucket:
    name: ${env:PALETTE_AWS_STORAGE_BUCKET_NAME}
    serverSideEncryption: AES256
  environment:
      PORT: ${env:PORT}
      NODE_ENV: ${env:NODE_ENV}
      JWT_SECRET: ${env:JWT_SECRET}
      SALESFORCE_GRANT_TYPE: ${env:SALESFORCE_GRANT_TYPE}
      SALESFORCE_CLIENT_ID: ${env:SALESFORCE_CLIENT_ID}
      SALESFORCE_CLIENT_SECRET: ${env:SALESFORCE_CLIENT_SECRET}
      SALESFORCE_USERNAME: ${env:SALESFORCE_USERNAME}
      SALESFORCE_PASSWORD: ${env:SALESFORCE_PASSWORD}
      UTILITY_NOTIFICATION_RECIPIENTS: ${env:UTILITY_NOTIFICATION_RECIPIENTS}
      PALETTE_SERVICE_NAME: ${env:PALETTE_SERVICE_NAME}
      PALETTE_AWS_SQS_NOTIFICATION_QUEUE_URL: ${env:PALETTE_AWS_SQS_NOTIFICATION_QUEUE_URL}
      PALETTE_AWS_REGION: ${env:PALETTE_AWS_REGION}
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: ${env:AWS_NODEJS_CONNECTION_REUSE_ENABLED}

functions:
  util:
    handler: dist/lambda.handler
    events:
      - http:
          method: POST
          path: util/contact
          cors: true
      - http:
          method: POST
          path: util/feedback
          cors: true
      - http:
          method: POST
          path: util/report/issue
          cors: true
      - http:
          method: GET
          path: util/guides
          cors: true
      - http:
          method: GET
          path: notifications
          cors: true
      - http:
          method: GET
          path: notifications/{id}
          request: 
            parameters:
              paths: 
                id: true
          cors: true
      - http:
          method: PATCH
          path: notifications/readall
          cors: true
      - http:
          method: PATCH
          path: notifications/read/{id}
          request: 
            parameters:
              paths: 
                id: true
          cors: true
      - http:
          method: DELETE
          path: notifications/deleteAll
          cors: true
